### PR TITLE
Fixes #137. Uses variants.instead of variant names

### LINKED ISSUE #137: NPE with multiple flavor dimensions
I get this exception with 1.0.0 in a project with multiple flavor dimensions. It seems that the variant which is looked up by name is null.

```
Caused by: java.lang.NullPointerException: Cannot get property 'name' on null object
        at org.robolectric.gradle.RobolectricPlugin$_apply_closure1.doCall(RobolectricPlugin.groovy:29)
```

### PR DESCRIPTION
**Pull request by castorflex**
Using `.all` will execute the closure for all the future items too. [See the doc](https://gradle.org/docs/current/javadoc/org/gradle/api/DomainObjectCollection.html#all(org.gradle.api.Action))

This should fix #137

### CODE REVIEW

**Comment by erd** [comment]
I'm happy to merge this, but I'd like to have a regression test to go along with it.

**Comment by edisonw** [comment]
+1 on the fix.

**Comment by frownlee** [comment]
I would recommend merging and publishing 1.0.1 rather than waiting for the regression test. This seems like a fairly major bug (it prevents any use of the project, robolectric or otherwise).

**Comment by erd** [comment]
> I would recommend merging and publishing 1.0.1 rather than waiting for the regression test. This seems like a fairly major bug (it prevents any use of the project, robolectric or otherwise).

Without some sort of regression test, it will get broken in the future. I'd rather take a few extra days and have something that's well tested.

**Comment by erd** [comment]
Solved by #139.

**Pull request closed without merging**
